# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76dcaa0e5d242dd79caa4e4615877c35ca8e0351606d2fc03041dafa28fa21fd65c9c8a3cbaead69f7f547b69d427e25baa3c22ad0fe1df87300796537de6314

test:
  secret_key_base: be60b83f0e7c0b2db9d293642f98f9b81426b31f41b5c856c7b25299e3e85186ab9a816fe66415bb759a985e3961a808931d4f426fd684b5e5eeb3152d85af01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
